name: Prefect Flows Deployment Pipeline
on:
  workflow_dispatch:

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY}}
  PREFECT_WORKSPACE_ID: ${{ secrets.PREFECT_WORKSPACE_ID}}
  PREFECT_ACCOUNT_ID: ${{ secrets.PREFECT_ACCOUNT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Python dependencies
        run: |
          pip install -r infra/requirements.txt

      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{ env.PREFECT_API_KEY }} 
          prefect config set PREFECT_API_URL="https://api.prefect.cloud/api/accounts/${{ env.PREFECT_ACCOUNT_ID }}/workspaces/${{ env.PREFECT_WORKSPACE_ID }}"

      - name: Deploy flows to Prefect Cloud
        id: deploy
        run: |
          prefect --no-prompt deploy
